//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationForWCFCalcService.ServiceReferenceCalc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCalc.ICalcService")]
    public interface ICalcService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/AddOne", ReplyAction="http://tempuri.org/ICalcService/AddOneResponse")]
        int AddOne();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/AddOne", ReplyAction="http://tempuri.org/ICalcService/AddOneResponse")]
        System.Threading.Tasks.Task<int> AddOneAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/Add", ReplyAction="http://tempuri.org/ICalcService/AddResponse")]
        int Add(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/Add", ReplyAction="http://tempuri.org/ICalcService/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/SubOne", ReplyAction="http://tempuri.org/ICalcService/SubOneResponse")]
        int SubOne();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/SubOne", ReplyAction="http://tempuri.org/ICalcService/SubOneResponse")]
        System.Threading.Tasks.Task<int> SubOneAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/Sub", ReplyAction="http://tempuri.org/ICalcService/SubResponse")]
        int Sub(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/Sub", ReplyAction="http://tempuri.org/ICalcService/SubResponse")]
        System.Threading.Tasks.Task<int> SubAsync(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/GetResult", ReplyAction="http://tempuri.org/ICalcService/GetResultResponse")]
        int GetResult();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/GetResult", ReplyAction="http://tempuri.org/ICalcService/GetResultResponse")]
        System.Threading.Tasks.Task<int> GetResultAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/Clear", ReplyAction="http://tempuri.org/ICalcService/ClearResponse")]
        void Clear();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/Clear", ReplyAction="http://tempuri.org/ICalcService/ClearResponse")]
        System.Threading.Tasks.Task ClearAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalcServiceChannel : WebApplicationForWCFCalcService.ServiceReferenceCalc.ICalcService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcServiceClient : System.ServiceModel.ClientBase<WebApplicationForWCFCalcService.ServiceReferenceCalc.ICalcService>, WebApplicationForWCFCalcService.ServiceReferenceCalc.ICalcService {
        
        public CalcServiceClient() {
        }
        
        public CalcServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddOne() {
            return base.Channel.AddOne();
        }
        
        public System.Threading.Tasks.Task<int> AddOneAsync() {
            return base.Channel.AddOneAsync();
        }
        
        public int Add(int i) {
            return base.Channel.Add(i);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int i) {
            return base.Channel.AddAsync(i);
        }
        
        public int SubOne() {
            return base.Channel.SubOne();
        }
        
        public System.Threading.Tasks.Task<int> SubOneAsync() {
            return base.Channel.SubOneAsync();
        }
        
        public int Sub(int i) {
            return base.Channel.Sub(i);
        }
        
        public System.Threading.Tasks.Task<int> SubAsync(int i) {
            return base.Channel.SubAsync(i);
        }
        
        public int GetResult() {
            return base.Channel.GetResult();
        }
        
        public System.Threading.Tasks.Task<int> GetResultAsync() {
            return base.Channel.GetResultAsync();
        }
        
        public void Clear() {
            base.Channel.Clear();
        }
        
        public System.Threading.Tasks.Task ClearAsync() {
            return base.Channel.ClearAsync();
        }
    }
}
